language: php
php:
    - 7.2
    - nightly
matrix:
    allow_failures:
        - php: nightly
jdk:
    - oraclejdk7
before_script:
    - wget dist.neo4j.org/neo4j-community-2.2.5-unix.tar.gz
    - tar -xzf neo4j-community-2.2.5-unix.tar.gz
    - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.5/conf/neo4j-server.properties
    - neo4j-community-2.2.5/bin/neo4j start
    - composer install
script: phpunit --coverage-clover=coverage.clover
after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
notifications:
    slack: innmind:nAiLaAi6RU4wGEAdL6FuKdyF
after_success:
    - bash <(curl -s https://codecov.io/bash)
